// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsK3Zh7EiyyvEpK7fJQSkWR3lZeIG6jGI',
    appId: '1:232516093543:web:19a4ed488cae9cd5e336c2',
    messagingSenderId: '232516093543',
    projectId: 'todo-6f0f6',
    authDomain: 'todo-6f0f6.firebaseapp.com',
    storageBucket: 'todo-6f0f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2BZMs2Hge-bUSXTEYDclhhKmKg80wGs',
    appId: '1:232516093543:android:5bb7c4ccd3706d00e336c2',
    messagingSenderId: '232516093543',
    projectId: 'todo-6f0f6',
    storageBucket: 'todo-6f0f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK72RbD0heMO1d1UIAp2zdvzT_kPHbev4',
    appId: '1:232516093543:ios:e42940feb1f8aa47e336c2',
    messagingSenderId: '232516093543',
    projectId: 'todo-6f0f6',
    storageBucket: 'todo-6f0f6.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK72RbD0heMO1d1UIAp2zdvzT_kPHbev4',
    appId: '1:232516093543:ios:e42940feb1f8aa47e336c2',
    messagingSenderId: '232516093543',
    projectId: 'todo-6f0f6',
    storageBucket: 'todo-6f0f6.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsK3Zh7EiyyvEpK7fJQSkWR3lZeIG6jGI',
    appId: '1:232516093543:web:c9147226205fe6e2e336c2',
    messagingSenderId: '232516093543',
    projectId: 'todo-6f0f6',
    authDomain: 'todo-6f0f6.firebaseapp.com',
    storageBucket: 'todo-6f0f6.firebasestorage.app',
  );
}
